### ISSUE TITLE
Manifest requires TAO 9.0.0

### ISSUE THREAD

**Issue by TailyFair** [oat-sa/extension-tao-devtools#96]
Manifest.php file requires TAO version higher than 9.0.0. This breaks installation of devtools.

**Comment by TailyFair** [comment]
Changed TAO version required to 3.0.0

**Comment by krampstudio** [comment]
This dependency is valid. it depends which version of TAO you have. See https://github.com/oat-sa/extension-tao-devtools/issues/75
